[package]
name = "bw-img"
version = "0.1.0"
edition = "2021"

[features]
default = ["gz", "img"]
gz = ["flate2"]
img = ["image"]

[dependencies]
thiserror = "*"
flate2 = { version = "*", optional = true }
image = { version = "*", optional = true }
